### PR TITLE
DMA test to show difference between X->Y and X->X transfer

### PR DESCRIPTION
**Pull request by notogawa**
Without NOP loop, X->X will be fail.

### CODE REVIEW

**Comment by Terminus-IMRC** [comment]
According to the Architecture Reference Manual p.24,

> For reads, the user programs the exact number required.
> The user must make sure that all reads that are programmed are ‘consumed’ by the shader prior to a program end.

So you should call `setup_vpm_read` with `nrows=1`.

In addition, you should read `vpm_ld_wait` for each DMA load.

**Comment by notogawa** [comment]
When copy & paste vpm read/write setup from another source, I miss to fix row count.
Thx!

**Comment by Terminus-IMRC** [comment]
LGTM

**Comment by nineties** [comment]
Thx.

**Pull request merged**
